# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, "8.0"  #平台信息


target 'swiftUse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks! #去掉注释 #使用的三方库

pod 'Alamofire'
pod 'MBProgressHUD'







  # Pods for swiftUse

  target 'swiftUseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
